server:
  port: ${CUSTOM.SERVER.PORT:9000}

encrypt:
  key: mtc-secret-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
