server:
  port: ${CUSTOM.SERVER.PORT:9000}

encrypt:
  key: mtc-secret-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://eureka-server:8761/eureka}
